export const DEFAULT = '/'
export const HOME = '/home'
export const PROFILE = '/profile'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const OAUTH = '/oauth/success'
export const MESSAGE = '/message'