export const DEFAULT = '/'
export const HOME = '/home'
export const LOGIN = '/login'
export const REGISTER = '/register'
export const OAUTH = '/oauth/success'
export const MESSAGE = '/message'
export const ERROR = '/error'
export const CONTENT = '/notes'